  version: "3"
  services:
    app:
      container_name: app
      build: .
      restart: on-failure
      expose:
        - '8081'
      ports:
        - '8080:8080'
      volumes:
        - ./:/app
      depends_on:
        - mongo
      networks:
        - backend
    mongo:
      image: mongo
      container_name: mongodb
      environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=nerb
      volumes:
       - "mongodata:/data/db"
      ports:
      - '27017:27017'

  # Networks to be created to facilitate communication between containers
  networks:
    backend:
      driver: bridge

  volumes:
     mongodata:

