  version: "3"
  services:
    app:
      container_name: app
      build: .
      environment:
        - APP_ENV=development
      #restart: on-failure
      expose:
        - '8080'
      ports:
        - '8000:8080'
      volumes:
        - ./:/app
      depends_on:
        - mongodb
      links:
        - mongodb
      networks:
        - backend
    mongodb:
      image: mongo
      container_name: mongodb
      environment:
       - MONGO_INITDB_ROOT_USERNAME=user
       - MONGO_INITDB_ROOT_PASSWORD=nerb
      networks:
        - backend
      volumes:
       - "mongodata:/data/db"
      ports:
      - '27017:27017'

  # Networks to be created to facilitate communication between containers
  networks:
    backend:
      driver: bridge

  volumes:
     mongodata:

